name: Open Test Pull Request

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  open-demo-pr:
    name: open-demo-pr
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: setup git-user data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      -
        name: commit changes
        run: |
          git checkout -b bug/matches-times
          git apply .github/demo-pr/changes.patch
          git add .
          git commit -m 'fix: display correct times in the matches table'
      -
        name: push changes
        run: git push -f origin bug/matches-times
      -
        name: open pull request
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          gh pr create \
            --base main \
            --head bug/matches-times \
            --title 'Show local times for match dates' \
            --body-file .github/demo-pr/body.md \
            --label bug \
            --reviewer ${{github.actor}}
